### ISSUE TITLE
Error 🤕

### ISSUE THREAD

**Issue by Clinton-Abraham** [prgofficial/URLuploader-With-Hotstar#12]
2021-03-16T11:09:56.603164+00:00 app[worker.1]: Traceback (most recent call last):
2021-03-16T11:09:56.603176+00:00 app[worker.1]:   File "/app/bot.py", line 39, in <module>
2021-03-16T11:09:56.603300+00:00 app[worker.1]:     app.run()
2021-03-16T11:09:56.603316+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/run.py", line 61, in run
2021-03-16T11:09:56.603451+00:00 app[worker.1]:     self.start()
2021-03-16T11:09:56.603466+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-03-16T11:09:56.603593+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-03-16T11:09:56.603607+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-03-16T11:09:56.603859+00:00 app[worker.1]:     return future.result()
2021-03-16T11:09:56.603875+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
2021-03-16T11:09:56.604000+00:00 app[worker.1]:     await self.initialize()
2021-03-16T11:09:56.604016+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2021-03-16T11:09:56.604136+00:00 app[worker.1]:     self.load_plugins()
2021-03-16T11:09:56.604151+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 714, in load_plugins
2021-03-16T11:09:56.605896+00:00 app[worker.1]:     module = import_module(module_path)
2021-03-16T11:09:56.605898+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-03-16T11:09:56.605899+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-03-16T11:09:56.605899+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-03-16T11:09:56.605900+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-03-16T11:09:56.605900+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-03-16T11:09:56.605900+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-03-16T11:09:56.605901+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
2021-03-16T11:09:56.605901+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-03-16T11:09:56.605902+00:00 app[worker.1]:   File "/app/plugins/cb_buttons.py", line 14, in <module>
2021-03-16T11:09:56.605902+00:00 app[worker.1]:     from plugins.help_text import cancel
2021-03-16T11:09:56.605902+00:00 app[worker.1]:   File "/app/plugins/help_text.py", line 32, in <module>
2021-03-16T11:09:56.605903+00:00 app[worker.1]:     from plugins.rename_file import rename_doc
2021-03-16T11:09:56.605904+00:00 app[worker.1]:   File "/app/plugins/rename_file.py", line 30, in <module>
2021-03-16T11:09:56.605905+00:00 app[worker.1]:     from database.database import *
2021-03-16T11:09:56.605905+00:00 app[worker.1]:   File "/app/database/database.py", line 24, in <module>
2021-03-16T11:09:56.605906+00:00 app[worker.1]:     SESSION = start()
2021-03-16T11:09:56.605906+00:00 app[worker.1]:   File "/app/database/database.py", line 17, in start
2021-03-16T11:09:56.605906+00:00 app[worker.1]:     engine = create_engine(Config.DB_URI, client_encoding="utf8")
2021-03-16T11:09:56.605907+00:00 app[worker.1]:   File "<string>", line 2, in create_engine
2021-03-16T11:09:56.605940+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
2021-03-16T11:09:56.606100+00:00 app[worker.1]:     return fn(*args, **kwargs)
2021-03-16T11:09:56.606101+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 520, in create_engine
2021-03-16T11:09:56.606302+00:00 app[worker.1]:     entrypoint = u._get_entrypoint()
2021-03-16T11:09:56.606306+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
2021-03-16T11:09:56.606534+00:00 app[worker.1]:     cls = registry.load(name)
2021-03-16T11:09:56.606537+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 341, in load
2021-03-16T11:09:56.606699+00:00 app[worker.1]:     raise exc.NoSuchModuleError(
2021-03-16T11:09:56.606741+00:00 app[worker.1]: sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
2021-03-16T11:09:56.788616+00:00 heroku[worker.1]: Process exited with status 1
2021-03-16T11:09:56.866179+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by prgofficial** [comment]
🤔🤔 redeploy once more! Using the deploy button, and check if error persists!

**Comment by Clinton-Abraham** [comment]
Lots of time Re-deployed same error occurred 😥

**Comment by Clinton-Abraham** [comment]
![IMG_20210316_171752](https://user-images.githubusercontent.com/70835540/111304316-9a22bf80-867b-11eb-8a14-0b0d30f54873.jpg)
![Uploading Screenshot_2021-03-16-17-16-26-576_com.android.chrome.jpg…]()

**Comment by prgofficial** [comment]
Have you edited something???

**Comment by prgofficial** [comment]
And send your config vars screenshot!  Remember to strike out the credentials

**Comment by Clinton-Abraham** [comment]
No bro...🥺

**Comment by Clinton-Abraham** [comment]
![Screenshot_2021-03-16-17-49-24-069_com android chrome](https://user-images.githubusercontent.com/70835540/111307850-fdaeec00-867f-11eb-99e3-225b83d98445.jpg)

**Comment by prgofficial** [comment]
Contact in my support group! @TroJanzSupport

**Comment by Clinton-Abraham** [comment]
Ok bro.. thank u 😊

**Comment by prgofficial** [comment]
Deploy now n check!! 

added a temp [fix](https://github.com/prgofficial/URLuploader-With-Hotstar/commit/66ebd408f99effffc87d2b36d130045118f1fb1c)

**Comment by Clinton-Abraham** [comment]
Thank u bro...❤️
